version: '3.3'
services:
  #PHP
  php:
    build:
      context: .
      dockerfile: dockerfiles/php/Dockerfile
    container_name: bundles-be
    restart: always
    env_file:
      - ./resources/.env
    volumes:
      - "./resources:/app:cached"

  #NGNIX
  ngnix:
    image: nginx:1.13-alpine
    container_name: bundles-svc
    restart: always
    ports:
      - "80"
    env_file:
      - ./resources/.env
    volumes:
      - "./dockerfiles/nginx/project.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./resources:/app:cached"
    depends_on:
      - php
    networks:
      - default

networks:
  default:
    external:
      name: apis
